# Generated by Django 2.2.9 on 2020-01-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0002_minutes_assoc_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document', verbose_name='Minutes PDF'),
        ),
    ]
