# Generated by Django 2.2.9 on 2020-01-12 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0003_auto_20200112_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='assoc_agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agendas.Agenda', verbose_name='Associated Agenda'),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document', verbose_name='Minutes PDF'),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='general_or_special',
            field=models.CharField(choices=[('general', 'General session'), ('special', 'Special session'), ('notice', 'Notice of Public Hearing'), ('canceled', 'Cancelled session')], default='general', max_length=10, null=True),
        ),
    ]
