# Generated by Django 2.2.9 on 2020-01-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0004_auto_20200112_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='general_or_special',
            field=models.CharField(choices=[('regular', 'Regular session'), ('special', 'Special session'), ('notice', 'Notice of Public Hearing'), ('canceled', 'Cancelled session')], default='general', max_length=10, null=True),
        ),
    ]
