# Generated by Django 2.2.9 on 2020-01-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0005_auto_20200113_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minutes',
            old_name='general_or_special',
            new_name='regular_or_special',
        ),
    ]
