# Generated by Django 2.2.9 on 2020-01-15 23:43

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarpage',
            name='top_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
