# Generated by Django 2.2.9 on 2020-01-15 07:00

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayspage',
            name='submenutitle',
            field=models.CharField(max_length=255, null=True, verbose_name='Submenu title'),
        ),
        migrations.AddField(
            model_name='holidayspage',
            name='text',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Bottom additional text'),
        ),
    ]
