# Generated by Django 2.2.9 on 2020-01-15 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_auto_20200115_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidayspage',
            old_name='text',
            new_name='bottom_text',
        ),
    ]
