# Generated by Django 2.2.9 on 2020-01-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0003_auto_20200115_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidayspage',
            name='top_heading',
            field=models.CharField(max_length=255, null=True, verbose_name='Heading above table'),
        ),
    ]
