# Generated by Django 2.2.9 on 2020-01-05 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffmember_staff_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='grade',
            field=models.CharField(blank=True, help_text='If the staff member is a teacher, enter a grade (K - 6). \n        Otherwise add a job title or description.', max_length=100, verbose_name='Grade or job description'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='staff_category',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('specialist', 'Specialist'), ('office', 'Office Staff'), ('other', 'Other')], default='teacher', max_length=100, null=True),
        ),
    ]
