# Generated by Django 2.2.9 on 2020-01-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200113_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='ext',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone extension'),
        ),
    ]
