# Generated by Django 2.2.9 on 2020-01-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20200113_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='ext',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Phone extension'),
        ),
    ]
