# Generated by Django 2.2.9 on 2020-01-13 19:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('staff', '0007_testorderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='ext',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='staff_category',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='title',
        ),
        migrations.RemoveField(
            model_name='testorderable',
            name='name',
        ),
        migrations.RemoveField(
            model_name='testorderable',
            name='page',
        ),
        migrations.RemoveField(
            model_name='testorderable',
            name='url',
        ),
        migrations.AddField(
            model_name='testorderable',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='testorderable',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='testorderable',
            name='ext',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Phone extension'),
        ),
        migrations.AddField(
            model_name='testorderable',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='testorderable',
            name='grade',
            field=models.CharField(blank=True, help_text='If the staff member is a teacher, enter a grade (K - 6). \n        Otherwise add a job title or description.', max_length=100, verbose_name='Grade or job description'),
        ),
        migrations.AddField(
            model_name='testorderable',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testorderable',
            name='parent_model',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_member', to='staff.StaffMember'),
        ),
        migrations.AddField(
            model_name='testorderable',
            name='title',
            field=models.CharField(choices=[('ms', 'Ms.'), ('mx', 'Mx.'), ('mr', 'Mr.'), ('dr', 'Dr.')], max_length=10, null=True),
        ),
    ]
