# Generated by Django 2.2.9 on 2020-01-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20200113_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffMember',
            new_name='StaffCategory',
        ),
    ]
