# Generated by Django 2.2.9 on 2020-01-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20200113_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffcategory',
            name='cat_title',
            field=models.CharField(max_length=255, null=True, verbose_name='Staff Category Name'),
        ),
        migrations.AlterField(
            model_name='testorderable',
            name='ext',
            field=models.CharField(max_length=3, null=True, verbose_name='Phone extension'),
        ),
        migrations.AlterField(
            model_name='testorderable',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testorderable',
            name='grade',
            field=models.CharField(blank=True, help_text='If the staff member is a teacher, enter a grade (K - 6). \n        Otherwise add a job title or description.', max_length=100, verbose_name='Grade or job title / description'),
        ),
    ]
