# Generated by Django 2.2.9 on 2020-01-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('staff', '0010_auto_20200113_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestOrderable',
            new_name='StaffOrderable',
        ),
        migrations.AlterModelOptions(
            name='staffcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
