# Generated by Django 2.2.9 on 2020-01-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_staffdirectorypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdirectorypage',
            name='submenutitle',
            field=models.CharField(max_length=255, null=True, verbose_name='Submenu title'),
        ),
    ]
