# Generated by Django 2.2.9 on 2020-01-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20200106_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementpage',
            name='date',
            field=models.DateField(null=True, verbose_name='Date of Announcement'),
        ),
    ]
