# Generated by Django 2.2.9 on 2020-01-08 02:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_announcementpage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementpage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('richtext_content', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'hr', 'link', 'document-link', 'center', 'font_color'], label='Text Content', required=True)), ('bg_color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'White'), ('lightgray', 'Light Gray')], label='Background Color'))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('bg_color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'White'), ('lightgray', 'Light Gray')], label='Background Color')), ('image_position', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center')], label='Image Position')), ('image_size', wagtail.core.blocks.ChoiceBlock(choices=[('large', 'Large'), ('medium', 'Medium')], label='Image Size'))], icon='image')), ('textimagesidebyside', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock(required=False)), ('bg_color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'White'), ('lightgray', 'LightGray')], label='Background Color')), ('position', wagtail.core.blocks.ChoiceBlock(choices=[('text_on_left', 'Text on Left'), ('text_on_right', 'Text on Right')], label='Text / Image Positioning')), ('vertical_position', wagtail.core.blocks.ChoiceBlock(choices=[('middle', 'Vertically Centered Content Within Section'), ('top', 'Content Starts at Top of Section')], label='Content Vertical Orientation'))])), ('textimagewrap', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock(required=False)), ('bg_color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'White'), ('lightgray', 'LightGray')], label='Background Color')), ('position', wagtail.core.blocks.ChoiceBlock(choices=[('image_on_left', 'Image on Left'), ('image_on_right', 'Image on Right')], label='Text / Image Positioning'))]))], null=True),
        ),
        migrations.AlterField(
            model_name='textandimagepage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.StructBlock([('richtext_content', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'hr', 'link', 'document-link', 'center', 'font_color'], label='Text Content', required=True)), ('bg_color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'White'), ('lightgray', 'Light Gray')], label='Background Color'))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('bg_color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'White'), ('lightgray', 'Light Gray')], label='Background Color')), ('image_position', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('center', 'Center')], label='Image Position')), ('image_size', wagtail.core.blocks.ChoiceBlock(choices=[('large', 'Large'), ('medium', 'Medium')], label='Image Size'))], icon='image')), ('textimagesidebyside', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock(required=False)), ('bg_color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'White'), ('lightgray', 'LightGray')], label='Background Color')), ('position', wagtail.core.blocks.ChoiceBlock(choices=[('text_on_left', 'Text on Left'), ('text_on_right', 'Text on Right')], label='Text / Image Positioning')), ('vertical_position', wagtail.core.blocks.ChoiceBlock(choices=[('middle', 'Vertically Centered Content Within Section'), ('top', 'Content Starts at Top of Section')], label='Content Vertical Orientation'))])), ('textimagewrap', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock(required=False)), ('bg_color', wagtail.core.blocks.ChoiceBlock(choices=[('white', 'White'), ('lightgray', 'LightGray')], label='Background Color')), ('position', wagtail.core.blocks.ChoiceBlock(choices=[('image_on_left', 'Image on Left'), ('image_on_right', 'Image on Right')], label='Text / Image Positioning'))]))]),
        ),
    ]
