# Generated by Django 2.2.9 on 2020-01-09 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('stream', '0006_dummypage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyPage',
        ),
    ]
