# Generated by Django 2.2.9 on 2020-01-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('home', '0002_homepage_agenda_chooser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='agenda_chooser',
        ),
        migrations.AddField(
            model_name='homepage',
            name='board_agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Select the active board agenda that the homepage will link to'),
        ),
    ]
