# Generated by Django 2.2.9 on 2020-01-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('general_or_special', models.CharField(choices=[('general', 'General'), ('special', 'Special')], default='general', max_length=10, null=True)),
                ('agenda_or_minutes', models.CharField(choices=[('agenda', 'Agenda'), ('minutes', 'Minutes')], default='agenda', max_length=10, null=True)),
            ],
        ),
    ]
