# Generated by Django 2.2.9 on 2020-01-12 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_auto_20200106_0214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minutes',
            options={'verbose_name_plural': 'Minutes'},
        ),
    ]
