# Generated by Django 2.2.9 on 2020-01-12 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('agendas', '0004_auto_20200112_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='assoc_minutes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
