# Generated by Django 2.2.9 on 2020-01-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0002_minutes_assoc_agenda'),
        ('agendas', '0009_auto_20200112_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='assoc_minutes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='minutes.Minutes'),
        ),
    ]
