# Generated by Django 2.2.9 on 2020-01-12 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('agendas', '0011_auto_20200112_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendasAndMinutesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('submenutitle', models.CharField(max_length=100, null=True, verbose_name='Submenu title')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='assoc_minutes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='minutes.Minutes', verbose_name='Associated minutes (Not required at time Agenda is created)'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document', verbose_name='Agenda PDF'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='general_or_special',
            field=models.CharField(choices=[('general', 'General session'), ('special', 'Special session'), ('notice', 'Notice of Public Hearing'), ('canceled', 'Cancelled session')], default='general', max_length=10, null=True),
        ),
    ]
