# Generated by Django 2.2.9 on 2020-01-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0012_auto_20200112_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='general_or_special',
        ),
        migrations.AddField(
            model_name='agenda',
            name='regular_or_special',
            field=models.CharField(choices=[('regular', 'Regular session'), ('special', 'Special session'), ('notice', 'Notice of Public Hearing'), ('canceled', 'Cancelled session')], default='regular', max_length=10, null=True, verbose_name='Agenda type'),
        ),
    ]
